<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_HIGOspotIntegrated Digital AgencyWiFi Advertising</name>
   <tag></tag>
   <elementGuidId>3e8dd405-d948-4224-82ab-519765dff789</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'service' and (text() = 'HIGOspotIntegrated Digital AgencyWiFi Advertising' or . = 'HIGOspotIntegrated Digital AgencyWiFi Advertising')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='service']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;service&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c93bfa25-3137-41cd-a7a0-600ebbab7801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service</value>
      <webElementGuid>0a6cc1d4-818d-408f-ad87-58c82ac3727f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full appearance-none rounded border px-2.5 py-1.5 text-sm</value>
      <webElementGuid>b8729b75-13c4-441a-a0dc-0acdbfc6c1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HIGOspotIntegrated Digital AgencyWiFi Advertising</value>
      <webElementGuid>1a5b6fa1-55bd-4449-8b06-c2e20a56708c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid gap-6 pt-safearea grid-content @4xl/page:grid-cols-2 @4xl/page:pb-safearea @4xl/page:pt-safearea-2x&quot;]/section[@class=&quot;grid&quot;]/div[@class=&quot;grid min-h-96 content-start gap-4 rounded-3xl bg-white p-6&quot;]/form[@class=&quot;grid gap-4&quot;]/div[@class=&quot;grid grid-flow-row gap-1&quot;]/div[@class=&quot;relative&quot;]/select[@class=&quot;w-full appearance-none rounded border px-2.5 py-1.5 text-sm&quot;]</value>
      <webElementGuid>205dd0ac-d86f-4177-bc4c-2f0f6e1224fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='service']</value>
      <webElementGuid>099966db-e764-4e13-8b25-39c32975d9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan yang ingin ditanyakan'])[1]/following::select[1]</value>
      <webElementGuid>961b7b69-927d-4040-b31c-52aebf090fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama perusahaan/lokasi/event/brand'])[1]/following::select[1]</value>
      <webElementGuid>9d98c366-beea-43a1-8390-3ee076ce8eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan'])[1]/preceding::select[1]</value>
      <webElementGuid>182f247d-770a-4c0d-837b-1cf15553f8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>e3416ac5-54fc-4661-9084-c1d6e2fbd167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4f5b7ae1-6352-4601-b7d2-35b1ef511595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'service' and (text() = 'HIGOspotIntegrated Digital AgencyWiFi Advertising' or . = 'HIGOspotIntegrated Digital AgencyWiFi Advertising')]</value>
      <webElementGuid>1689bfeb-485b-4848-ba10-36a08bbecf58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
