<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download Full Report</name>
   <tag></tag>
   <elementGuidId>baac83c0-af9a-444b-b29c-414b7b506473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Download Full Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12ead784-abe6-44ab-80b9-fcd96ff394b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-fit max-w-full rounded-full bg-tint-1 px-3 py-2 text-sm font-medium text-primary mt-4 hidden @3xl/section:grid</value>
      <webElementGuid>7190dbfc-0208-4922-8e5b-f754dc5e3c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc228974-e37f-4623-951c-10193eb6df45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>b2266de8-2691-47c4-84d3-aabdd8b13fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>02a85094-3178-4030-a595-ffee3a79d26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r0:</value>
      <webElementGuid>da8308e2-9680-491b-9980-d0ac2b7fc827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>c6b69401-0d19-48c4-ab70-4819776059a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Full Report</value>
      <webElementGuid>751e4a5e-16ce-4c9c-9492-02218468d14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/main[@class=&quot;gap-y-6 @container/page grid-container&quot;]/div[@class=&quot;grid-full&quot;]/section[@class=&quot;grid @container/section grid-full relative gap-8&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;@container/section-content grid gap-8 grid-content @3xl/section:grid-cols-2 @3xl/section:gap-0&quot;]/div[@class=&quot;grid @3xl/section:items-center&quot;]/div[@class=&quot;relative max-w-full delay-200 duration-700 animate-in fade-in slide-in-from-bottom-6 @3xl/section:aspect-square @3xl/section:w-120 @3xl/section:rounded-full @3xl/section:bg-primary&quot;]/div[@class=&quot;grid place-content-center items-center gap-3 @3xl/section:absolute @3xl/section:inset-20&quot;]/button[@class=&quot;w-fit max-w-full rounded-full bg-tint-1 px-3 py-2 text-sm font-medium text-primary mt-4 hidden @3xl/section:grid&quot;]</value>
      <webElementGuid>a1425398-c175-4c19-a609-f4798a68d6b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>db854683-0125-489b-bf5b-6ff234b58b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Source: Unsplash'])[1]/following::button[1]</value>
      <webElementGuid>32067ead-eddb-4e02-8e85-7c63ea06b970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Full Report'])[2]/preceding::button[1]</value>
      <webElementGuid>2b36a67e-772b-4774-b99e-0647745d2a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Full Report']/parent::*</value>
      <webElementGuid>cb514221-104e-4499-a701-85eb6917150d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3803301b-9212-40bb-8b05-4b53af78c14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Download Full Report' or . = 'Download Full Report')]</value>
      <webElementGuid>a8872331-0aeb-45b0-ac60-2331750a29d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
