<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company</name>
   <tag></tag>
   <elementGuidId>e8d16a76-bdd1-48cb-b697-8be4b61a034b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='company'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Company Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b07f28f5-ac4e-469c-9d15-50d58609d512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80</value>
      <webElementGuid>1b72e008-ea37-46c0-8366-671b7d45a1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a1c9dee9-0bd5-45df-a0e0-9d14a6d65264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d87ad70-69c1-470c-a8d0-eace79e9fd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Name</value>
      <webElementGuid>2b94a24d-202d-4d02-b206-270c5b423d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10f6c2a7-fc5f-437f-99b4-e5b5ec10a0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>3fea8309-cd4f-43ec-b84a-3cd99b0a553c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r0:&quot;)/form[@class=&quot;grid content-start gap-6 @container/form&quot;]/div[@class=&quot;grid grid-cols-1 gap-x-6 gap-y-6 @xl/form:grid-cols-2&quot;]/div[@class=&quot;grid grid-flow-row content-start gap-4&quot;]/input[@class=&quot;border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80&quot;]</value>
      <webElementGuid>15c72e2d-ada7-44a6-94b6-c886f046d3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='company'])[2]</value>
      <webElementGuid>4cf3f2a5-67ba-4453-b8ec-aae3ee537626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r0:']/form/div[2]/div[5]/input</value>
      <webElementGuid>a35f6dee-e55a-40fa-9349-ab93c564b055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/div[5]/input</value>
      <webElementGuid>132d2aa1-1e6f-4774-a795-b2fafc9d4c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Company Name' and @type = 'text' and @name = 'company']</value>
      <webElementGuid>11634985-0124-4153-a424-3b25e4da07f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
