<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone</name>
   <tag></tag>
   <elementGuidId>38a27fb7-9ac6-44e8-8808-013b3deedba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='phone'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Phone Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1711363f-539a-498e-80fa-333faa08d32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80</value>
      <webElementGuid>3ac3db61-1ed3-4672-a4aa-695464a5bace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>46666fde-6b63-4ead-b045-d1fc2cc41fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5a829a5-1e5c-4de4-abbb-406db93d505f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>2350ec3d-6875-4995-8368-ef028f90479b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3a1284f-ce2b-4734-9035-1b55b56fb56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>15fce844-10d9-446f-a435-7aa10c9e0cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r0:&quot;)/form[@class=&quot;grid content-start gap-6 @container/form&quot;]/div[@class=&quot;grid grid-cols-1 gap-x-6 gap-y-6 @xl/form:grid-cols-2&quot;]/div[@class=&quot;grid grid-flow-row content-start gap-4&quot;]/input[@class=&quot;border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80&quot;]</value>
      <webElementGuid>f627de41-6745-4145-ab36-05b93344cc77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='phone'])[2]</value>
      <webElementGuid>6aec56b8-83a0-40a6-89a1-8c871ac9e210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r0:']/form/div[2]/div[4]/input</value>
      <webElementGuid>98704575-601d-4834-a686-9975693bc1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/div[4]/input</value>
      <webElementGuid>38e7f717-b676-43dc-bde7-8bdcd2b18fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Phone Number' and @type = 'text' and @name = 'phone']</value>
      <webElementGuid>91b5b221-544f-4caf-8c06-5a3e33dea3d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
