<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_firstName</name>
   <tag></tag>
   <elementGuidId>80eb0a9d-fbae-41e7-b52f-a55798c2d7ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='firstName'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;First Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf230eed-e16f-49b0-9e52-235dae91d508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80</value>
      <webElementGuid>769a42d5-b148-43e7-b124-e2bf6099d4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f6434b37-ae3f-4113-93a9-c2628acb4ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>59265455-faa7-4250-99a1-3d4add5e7212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>139a788b-04eb-43e3-b5b8-bb14c872b5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>347ec908-4892-4068-90ce-fa8c8ce6f528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>6a638df1-7b06-48e1-9a30-71bfd0895fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r0:&quot;)/form[@class=&quot;grid content-start gap-6 @container/form&quot;]/div[@class=&quot;grid grid-cols-1 gap-x-6 gap-y-6 @xl/form:grid-cols-2&quot;]/div[@class=&quot;grid grid-flow-row content-start gap-4&quot;]/input[@class=&quot;border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80&quot;]</value>
      <webElementGuid>66a9c768-2a96-4552-8658-940a72456d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='firstName'])[2]</value>
      <webElementGuid>a98130a3-cf03-4d13-936f-ecddc97ac8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r0:']/form/div[2]/div/input</value>
      <webElementGuid>ae485821-4976-4e6d-b3f4-6fcc5035ef6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/div/input</value>
      <webElementGuid>296fca81-a9b7-45c3-83d7-713c98ddfb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'First Name' and @type = 'text' and @name = 'firstName']</value>
      <webElementGuid>21db09e5-18fc-4b67-9047-d1d521756857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
