<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_lastName</name>
   <tag></tag>
   <elementGuidId>6f8c27bb-3e57-4fbf-9195-7fe4b962c674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='lastName'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63a464a2-9373-4d18-afbd-60e76edcc91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80</value>
      <webElementGuid>4ffb3b1a-fe2f-4ded-9b29-3d24e963b0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d732e2aa-3c38-43ac-a8e3-7c93d5144eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10eba1eb-1b76-42b3-aeed-30d5b8f605f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>2533722f-08dd-4039-a734-212925755261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8eb0f4c5-2c79-42cd-8cee-de05c6cf7611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>a9e7feb6-6ca9-4ae7-a701-6e7e61e7b282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r0:&quot;)/form[@class=&quot;grid content-start gap-6 @container/form&quot;]/div[@class=&quot;grid grid-cols-1 gap-x-6 gap-y-6 @xl/form:grid-cols-2&quot;]/div[@class=&quot;grid grid-flow-row content-start gap-4&quot;]/input[@class=&quot;border-b border-white bg-transparent px-2 py-2 text-white outline-none placeholder:text-white/80&quot;]</value>
      <webElementGuid>9148fe9b-a454-403d-80a7-b1db01b9ad66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='lastName'])[2]</value>
      <webElementGuid>5a1ffd16-9949-4f9f-bdf8-f3e15f43c559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r0:']/form/div[2]/div[2]/input</value>
      <webElementGuid>6db13428-f02b-4787-9960-c29ddb0c65a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/div[2]/input</value>
      <webElementGuid>1c899034-a335-4edf-8096-401a380d3264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Last Name' and @type = 'text' and @name = 'lastName']</value>
      <webElementGuid>643b9830-afd8-4ca2-b09c-8af1a3f9289e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
