<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Tentang HIGO_text-white</name>
   <tag></tag>
   <elementGuidId>5bf427a2-2072-4925-80fe-dd5b3739f390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang HIGO'])[1]/preceding::*[name()='svg'][3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;HIGO&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f0b2e3c5-6d14-4525-8899-b875e01192e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>ef86111a-cdfe-419d-b269-d6e96f843301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 3324 805</value>
      <webElementGuid>16537173-4f78-4ef8-ab65-ed82e02a2a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>ef03befd-b98c-467d-9014-d9ca10c1cd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white</value>
      <webElementGuid>293d207f-fb72-4bb2-a389-e1aeec4ab2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/header[@class=&quot;grid grid-flow-col fixed inset-x-0 top-7 z-top grid-container&quot;]/div[@class=&quot;relative text-white @container/header grid-content&quot;]/div[@class=&quot;grid grid-cols-r-fill items-center rounded-3xl bg-primary px-7 @2xl/header:px-10&quot;]/a[@class=&quot;relative z-20&quot;]/svg[@class=&quot;text-white&quot;]</value>
      <webElementGuid>cea08093-0e9b-42f2-9fb4-5fe951fcdbd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang HIGO'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>7d1efc56-c42d-487f-a780-299f5584f4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang HIGO'])[2]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>af279a8b-48b2-49d0-a403-4afcc5ef26f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
