<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HIGOspot</name>
   <tag></tag>
   <elementGuidId>98b7b92c-f02d-4d1d-bd13-e8c14d19cfda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='WiFi Advertising'])[2]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:role=link[name=&quot;HIGOspot&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b1661778-311d-42ef-b795-baf81e1ca0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HIGOspot</value>
      <webElementGuid>c02b50bd-acb6-4015-a2e4-787f02111b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_7be8ac __variable_bf78da font-inter font-light&quot;]/header[@class=&quot;grid grid-flow-col fixed inset-x-0 top-7 z-top grid-container&quot;]/div[@class=&quot;relative text-white @container/header grid-content&quot;]/div[@class=&quot;grid grid-cols-r-fill items-center rounded-3xl bg-primary px-7 @2xl/header:px-10&quot;]/nav[@class=&quot;absolute inset-x-0 top-full grid -translate-y-6 grid-rows-[0fr] overflow-clip rounded-b-3xl bg-primary transition-[grid-template-rows] duration-300 peer-checked:grid peer-checked:grid-rows-[1fr] @4xl/header:static @4xl/header:translate-y-0 @4xl/header:grid-rows-none @4xl/header:justify-end @4xl/header:overflow-visible @4xl/header:rounded-t-3xl&quot;]/ul[@class=&quot;@4xl/header:min-h-auto col-start-1 col-end-1 row-start-1 row-end-1 grid min-h-0 grid-flow-row gap-x-5 divide-y divide-white/10 px-7 py-3 @2xl/header:px-10 @4xl/header:!col-auto @4xl/header:!row-auto @4xl/header:w-max @4xl/header:grid-flow-col @4xl/header:!divide-none @4xl/header:px-0 @4xl/header:py-0 @5xl:gap-x-10 [&amp;>*:first-child]:mt-6 @4xl/header:[&amp;>*:first-child]:mt-0&quot;]/li[@class=&quot;group/navigation-item relative grid font-anek-malayalam underline-offset-8 @4xl:decoration-blue-300 @4xl:hover:underline&quot;]/ul[@class=&quot;hidden w-full pb-4 peer-checked:grid @4xl/header:absolute @4xl/header:right-0 @4xl/header:top-full @4xl/header:hidden @4xl/header:w-max @4xl/header:-translate-y-1 @4xl/header:rounded-xl @4xl/header:bg-white @4xl/header:py-4 @4xl/header:text-primary @4xl/header:shadow-xl @4xl/header:group-hover/navigation-item:!grid @4xl/header:peer-checked:hidden&quot;]/li[@class=&quot;group/navigation-item relative grid font-anek-malayalam underline-offset-8 pl-4 @4xl/header:px-4 @4xl/header:transition-colors @4xl/header:duration-500 @4xl/header:hover:bg-violet-100&quot;]/label[@class=&quot;peer-checked:hidden&quot;]/a[@class=&quot;grid grid-cols-l-fill items-center py-1.5&quot;]/span[1]</value>
      <webElementGuid>e270fd12-4591-4a32-8c57-39de197dc43f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WiFi Advertising'])[2]/following::span[1]</value>
      <webElementGuid>442e0be8-610a-4011-b501-9b179f76a7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WiFi Advertising'])[1]/following::span[2]</value>
      <webElementGuid>549bdb40-dc02-4fc7-969a-476f70ce9c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIGOspot'])[2]/preceding::span[1]</value>
      <webElementGuid>9ca01030-c31e-429d-97a0-c9a4f6e899f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integrated Digital Agency'])[1]/preceding::span[2]</value>
      <webElementGuid>7f914cdc-81bd-461b-84ae-2ac577c0090e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HIGOspot']/parent::*</value>
      <webElementGuid>d6e9a4d5-b13e-46de-ace1-57d00a267aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/a/span</value>
      <webElementGuid>5b049a3c-4f06-4560-b19e-20eb0eeabeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'HIGOspot' or . = 'HIGOspot')]</value>
      <webElementGuid>91e15aa6-0c20-4b6e-b121-74f4e47e7042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
